services:
  backend:
    build:
      context: ./backend/astraScriptum
      dockerfile: Dockerfile
    container_name: backend-spring
    ports:
      - "8080:8080"
    environment:
      # Exemple : variables pour Spring (à adapter à ton projet)
      SPRING_PROFILES_ACTIVE: docker
      # SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ma_base
      # SPRING_DATASOURCE_USERNAME: user
      # SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend/astraFront
      dockerfile: Dockerfile
    container_name: frontend-vite
    ports:
      - "5173:5173"
    environment:
      # Vite peut utiliser cette variable pour appeler le back
      VITE_API_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
